import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "@/app/globals.css";
import Menue from "@/components/menue";
import Footer from "@/components/footer";




const outfit = Outfit({
  subsets: ["latin"], display: 'swap',
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <div>
          <Menue />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
